"""update playlist: add external_username, nullable owner_id

Revision ID: 12c1afd13ba7
Revises: e5633acdc0bb
Create Date: 2025-09-05 22:50:30.152548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c1afd13ba7'
down_revision: Union[str, Sequence[str], None] = 'e5633acdc0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('source', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'source')
    # ### end Alembic commands ###
