"""add is_active to users

Revision ID: 61d9aa63c1be
Revises: 12c1afd13ba7
Create Date: 2025-09-07 13:58:06.692323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d9aa63c1be'
down_revision: Union[str, Sequence[str], None] = '12c1afd13ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('jamendo_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'songs', ['jamendo_id'])
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'bio')
    op.drop_constraint(None, 'songs', type_='unique')
    op.drop_column('songs', 'jamendo_id')
    # ### end Alembic commands ###
