"""Remove isactive and createdat from users

Revision ID: af9a04454ab1
Revises: 3ad8eb2e7a19
Create Date: 2025-09-05 16:13:37.920506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'af9a04454ab1'
down_revision: Union[str, Sequence[str], None] = '3ad8eb2e7a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', mysql.TEXT(), nullable=True))
    op.add_column('users', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
    op.add_column('users', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
