"""add jamendo_id to songs

Revision ID: ca662caf0848
Revises: 03987f00b65c
Create Date: 2025-08-25 22:45:01.461885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca662caf0848'
down_revision: Union[str, Sequence[str], None] = '03987f00b65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('jamendo_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'songs', ['jamendo_id'])
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'songs', type_='unique')
    op.drop_column('songs', 'jamendo_id')
    # ### end Alembic commands ###
