"""add something

Revision ID: e0bbd556af98
Revises: 68636183c50c
Create Date: 2025-09-16 15:38:18.518376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0bbd556af98'
down_revision: Union[str, Sequence[str], None] = '68636183c50c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('source', sa.String(length=20), nullable=False))
    op.add_column('songs', sa.Column('jamendo_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'songs', ['jamendo_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='unique')
    op.drop_column('songs', 'jamendo_id')
    op.drop_column('playlists', 'source')
    # ### end Alembic commands ###
